### ISSUE TITLE
Gallery needs to be improved

### ISSUE THREAD

**Issue by siddhanathan** [OSCAV/cvRecognition#1]
Currently, the app records a video and displays the first frame of the video in the gallery. Instead, the app should allow a user to view every frame of the video, and delete individual frames if needed. Assigned to @bugsquad/cv

**Comment by xinpengliu** [comment]
tell me the steps

**Comment by siddhanathan** [comment]
@xinpengliu Well, basically, when you see a single capture on the gallery, the capture actually signifies a video and not a single frame. If the user can go into the video, and delete particular frames from the video capture, that would greatly improve the recognition process.
